import * as AWS from "aws-sdk";
import "dotenv/config";

const SESConfig = {
  accessKeyId: process.env.AWS_ACCESS_KEY,
  secretAccessKey: process.env.AWS_SECRET_KEY,
  region: process.env.AWS_REGION,
};

AWS.config.update(SESConfig);
AWS.config.correctClockSkew = true;
AWS.config.mediaconvert = {
  endpoint: process.env.AWS_ENDPOINT_CONVERT,
};

export class AWSMediaConvertService {
  private params;
  constructor(param?) {
    if (param) {
      this.params = {
        Queue: "Default",
        UserMetadata: {
          Customer: "Amazon",
        },
        Role: "arn:aws:iam::902282556220:role/service-role/MediaConvert_Default_Role",
        Settings: {
          TimecodeConfig: {
            Source: "ZEROBASED",
          },
          OutputGroups: [
            {
              CustomName: "name zzzz",
              Name: "Apple HLS",
              Outputs: [
                {
                  ContainerSettings: {
                    Container: "M3U8",
                    M3u8Settings: {
                      AudioFramesPerPes: 4,
                      PcrControl: "PCR_EVERY_PES_PACKET",
                      PmtPid: 480,
                      PrivateMetadataPid: 503,
                      ProgramNumber: 1,
                      PatInterval: 0,
                      PmtInterval: 0,
                      VideoPid: 481,
                      AudioPids: [
                        482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492,
                        493, 494, 495, 496, 497, 498,
                      ],
                    },
                  },
                  VideoDescription: {
                    Width: 1920,
                    ScalingBehavior: "DEFAULT",
                    Height: 1080,
                    TimecodeInsertion: "DISABLED",
                    AntiAlias: "ENABLED",
                    Sharpness: 50,
                    CodecSettings: {
                      Codec: "H_264",
                      H264Settings: {
                        InterlaceMode: "PROGRESSIVE",
                        ParNumerator: 1,
                        NumberReferenceFrames: 3,
                        Syntax: "DEFAULT",
                        FramerateDenominator: 1001,
                        GopClosedCadence: 1,
                        HrdBufferInitialFillPercentage: 90,
                        GopSize: 90,
                        Slices: 1,
                        GopBReference: "DISABLED",
                        HrdBufferSize: 12750000,
                        MaxBitrate: 4000000,
                        ParDenominator: 1,
                        EntropyEncoding: "CABAC",
                        FramerateControl: "SPECIFIED",
                        RateControlMode: "QVBR",
                        QvbrSettings: {
                          QvbrQualityLevel: 9,
                          QvbrQualityLevelFineTune: 0,
                        },
                        CodecProfile: "HIGH",
                        Telecine: "NONE",
                        FramerateNumerator: 30000,
                        MinIInterval: 0,
                        AdaptiveQuantization: "AUTO",
                        CodecLevel: "LEVEL_4",
                        FieldEncoding: "PAFF",
                        SceneChangeDetect: "ENABLED",
                        QualityTuningLevel: "SINGLE_PASS",
                        FramerateConversionAlgorithm: "DUPLICATE_DROP",
                        UnregisteredSeiTimecode: "DISABLED",
                        GopSizeUnits: "FRAMES",
                        ParControl: "SPECIFIED",
                        NumberBFramesBetweenReferenceFrames: 1,
                        RepeatPps: "DISABLED",
                      },
                    },
                    AfdSignaling: "NONE",
                    DropFrameTimecode: "ENABLED",
                    RespondToAfd: "NONE",
                    ColorMetadata: "INSERT",
                  },
                  AudioDescriptions: [
                    {
                      AudioTypeControl: "FOLLOW_INPUT",
                      CodecSettings: {
                        Codec: "AAC",
                        AacSettings: {
                          AudioDescriptionBroadcasterMix: "NORMAL",
                          Bitrate: 128000,
                          RateControlMode: "CBR",
                          CodecProfile: "LC",
                          CodingMode: "CODING_MODE_2_0",
                          RawFormat: "NONE",
                          SampleRate: 48000,
                          Specification: "MPEG4",
                        },
                      },
                      LanguageCodeControl: "FOLLOW_INPUT",
                      AudioType: 0,
                    },
                  ],
                  OutputSettings: {
                    HlsSettings: {
                      IFrameOnlyManifest: "EXCLUDE",
                    },
                  },
                  NameModifier: "1080p",
                },
                {
                  ContainerSettings: {
                    Container: "M3U8",
                    M3u8Settings: {
                      AudioFramesPerPes: 4,
                      PcrControl: "PCR_EVERY_PES_PACKET",
                      PmtPid: 480,
                      PrivateMetadataPid: 503,
                      ProgramNumber: 1,
                      PatInterval: 0,
                      PmtInterval: 0,
                      VideoPid: 481,
                      AudioPids: [
                        482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492,
                        493, 494, 495, 496, 497, 498,
                      ],
                    },
                  },
                  VideoDescription: {
                    Width: 1280,
                    ScalingBehavior: "DEFAULT",
                    Height: 720,
                    TimecodeInsertion: "DISABLED",
                    AntiAlias: "ENABLED",
                    Sharpness: 50,
                    CodecSettings: {
                      Codec: "H_264",
                      H264Settings: {
                        InterlaceMode: "PROGRESSIVE",
                        ParNumerator: 1,
                        NumberReferenceFrames: 3,
                        Syntax: "DEFAULT",
                        FramerateDenominator: 1001,
                        GopClosedCadence: 1,
                        HrdBufferInitialFillPercentage: 90,
                        GopSize: 90,
                        Slices: 1,
                        GopBReference: "DISABLED",
                        HrdBufferSize: 7500000,
                        MaxBitrate: 2500000,
                        SlowPal: "DISABLED",
                        ParDenominator: 1,
                        EntropyEncoding: "CABAC",
                        FramerateControl: "SPECIFIED",
                        RateControlMode: "QVBR",
                        QvbrSettings: {
                          QvbrQualityLevel: 9,
                          QvbrQualityLevelFineTune: 0,
                        },
                        CodecProfile: "MAIN",
                        Telecine: "NONE",
                        FramerateNumerator: 30000,
                        MinIInterval: 0,
                        AdaptiveQuantization: "AUTO",
                        CodecLevel: "LEVEL_3_1",
                        FieldEncoding: "PAFF",
                        SceneChangeDetect: "ENABLED",
                        QualityTuningLevel: "SINGLE_PASS",
                        FramerateConversionAlgorithm: "DUPLICATE_DROP",
                        UnregisteredSeiTimecode: "DISABLED",
                        GopSizeUnits: "FRAMES",
                        ParControl: "SPECIFIED",
                        NumberBFramesBetweenReferenceFrames: 1,
                        RepeatPps: "DISABLED",
                      },
                    },
                    AfdSignaling: "NONE",
                    DropFrameTimecode: "ENABLED",
                    RespondToAfd: "NONE",
                    ColorMetadata: "INSERT",
                  },
                  AudioDescriptions: [
                    {
                      AudioTypeControl: "FOLLOW_INPUT",
                      CodecSettings: {
                        Codec: "AAC",
                        AacSettings: {
                          AudioDescriptionBroadcasterMix: "NORMAL",
                          Bitrate: 96000,
                          RateControlMode: "CBR",
                          CodecProfile: "HEV1",
                          CodingMode: "CODING_MODE_2_0",
                          RawFormat: "NONE",
                          SampleRate: 48000,
                          Specification: "MPEG4",
                        },
                      },
                      LanguageCodeControl: "FOLLOW_INPUT",
                      AudioType: 0,
                    },
                  ],
                  OutputSettings: {
                    HlsSettings: {
                      IFrameOnlyManifest: "EXCLUDE",
                    },
                  },
                  NameModifier: "720p",
                },
                {
                  ContainerSettings: {
                    Container: "M3U8",
                    M3u8Settings: {
                      AudioFramesPerPes: 4,
                      PcrControl: "PCR_EVERY_PES_PACKET",
                      PmtPid: 480,
                      PrivateMetadataPid: 503,
                      ProgramNumber: 1,
                      PatInterval: 0,
                      PmtInterval: 0,
                      VideoPid: 481,
                      AudioPids: [
                        482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492,
                        493, 494, 495, 496, 497, 498,
                      ],
                    },
                  },
                  VideoDescription: {
                    Width: 854,
                    ScalingBehavior: "DEFAULT",
                    Height: 480,
                    TimecodeInsertion: "DISABLED",
                    AntiAlias: "ENABLED",
                    Sharpness: 50,
                    CodecSettings: {
                      Codec: "H_264",
                      H264Settings: {
                        InterlaceMode: "PROGRESSIVE",
                        ParNumerator: 1,
                        NumberReferenceFrames: 3,
                        Syntax: "DEFAULT",
                        FramerateDenominator: 1001,
                        GopClosedCadence: 1,
                        HrdBufferInitialFillPercentage: 90,
                        GopSize: 90,
                        Slices: 1,
                        GopBReference: "DISABLED",
                        MaxBitrate: 1500000,
                        SlowPal: "DISABLED",
                        ParDenominator: 1,
                        EntropyEncoding: "CABAC",
                        FramerateControl: "SPECIFIED",
                        RateControlMode: "QVBR",
                        QvbrSettings: {
                          QvbrQualityLevel: 9,
                          QvbrQualityLevelFineTune: 0,
                        },
                        CodecProfile: "MAIN",
                        Telecine: "NONE",
                        FramerateNumerator: 30000,
                        MinIInterval: 0,
                        AdaptiveQuantization: "AUTO",
                        CodecLevel: "LEVEL_3_1",
                        FieldEncoding: "PAFF",
                        SceneChangeDetect: "ENABLED",
                        QualityTuningLevel: "SINGLE_PASS",
                        FramerateConversionAlgorithm: "DUPLICATE_DROP",
                        UnregisteredSeiTimecode: "DISABLED",
                        GopSizeUnits: "FRAMES",
                        ParControl: "SPECIFIED",
                        NumberBFramesBetweenReferenceFrames: 1,
                        RepeatPps: "DISABLED",
                      },
                    },
                    AfdSignaling: "NONE",
                    DropFrameTimecode: "ENABLED",
                    RespondToAfd: "NONE",
                    ColorMetadata: "INSERT",
                  },
                  AudioDescriptions: [
                    {
                      AudioTypeControl: "FOLLOW_INPUT",
                      CodecSettings: {
                        Codec: "AAC",
                        AacSettings: {
                          AudioDescriptionBroadcasterMix: "NORMAL",
                          Bitrate: 96000,
                          RateControlMode: "CBR",
                          CodecProfile: "HEV1",
                          CodingMode: "CODING_MODE_2_0",
                          RawFormat: "NONE",
                          SampleRate: 48000,
                          Specification: "MPEG4",
                        },
                      },
                      LanguageCodeControl: "FOLLOW_INPUT",
                      AudioType: 0,
                    },
                  ],
                  OutputSettings: {
                    HlsSettings: {
                      IFrameOnlyManifest: "EXCLUDE",
                    },
                  },
                  NameModifier: "480p",
                },
                {
                  ContainerSettings: {
                    Container: "M3U8",
                    M3u8Settings: {
                      AudioFramesPerPes: 4,
                      PcrControl: "PCR_EVERY_PES_PACKET",
                      PmtPid: 480,
                      PrivateMetadataPid: 503,
                      ProgramNumber: 1,
                      PatInterval: 0,
                      PmtInterval: 0,
                      VideoPid: 481,
                      AudioPids: [
                        482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492,
                        493, 494, 495, 496, 497, 498,
                      ],
                    },
                  },
                  VideoDescription: {
                    Width: 640,
                    ScalingBehavior: "DEFAULT",
                    Height: 360,
                    TimecodeInsertion: "DISABLED",
                    AntiAlias: "ENABLED",
                    Sharpness: 50,
                    CodecSettings: {
                      Codec: "H_264",
                      H264Settings: {
                        InterlaceMode: "PROGRESSIVE",
                        ParNumerator: 1,
                        NumberReferenceFrames: 3,
                        Syntax: "DEFAULT",
                        FramerateDenominator: 1001,
                        GopClosedCadence: 1,
                        HrdBufferInitialFillPercentage: 90,
                        GopSize: 90,
                        Slices: 1,
                        GopBReference: "DISABLED",
                        MaxBitrate: 800000,
                        SlowPal: "DISABLED",
                        ParDenominator: 1,
                        EntropyEncoding: "CABAC",
                        FramerateControl: "SPECIFIED",
                        RateControlMode: "QVBR",
                        QvbrSettings: {
                          QvbrQualityLevel: 9,
                          QvbrQualityLevelFineTune: 0,
                        },
                        CodecProfile: "MAIN",
                        Telecine: "NONE",
                        FramerateNumerator: 30000,
                        MinIInterval: 0,
                        AdaptiveQuantization: "AUTO",
                        CodecLevel: "LEVEL_3_1",
                        FieldEncoding: "PAFF",
                        SceneChangeDetect: "ENABLED",
                        QualityTuningLevel: "SINGLE_PASS",
                        FramerateConversionAlgorithm: "DUPLICATE_DROP",
                        UnregisteredSeiTimecode: "DISABLED",
                        GopSizeUnits: "FRAMES",
                        ParControl: "SPECIFIED",
                        NumberBFramesBetweenReferenceFrames: 1,
                        RepeatPps: "DISABLED",
                      },
                    },
                    AfdSignaling: "NONE",
                    DropFrameTimecode: "ENABLED",
                    RespondToAfd: "NONE",
                    ColorMetadata: "INSERT",
                  },
                  AudioDescriptions: [
                    {
                      AudioTypeControl: "FOLLOW_INPUT",
                      CodecSettings: {
                        Codec: "AAC",
                        AacSettings: {
                          AudioDescriptionBroadcasterMix: "NORMAL",
                          Bitrate: 96000,
                          RateControlMode: "CBR",
                          CodecProfile: "HEV1",
                          CodingMode: "CODING_MODE_2_0",
                          RawFormat: "NONE",
                          SampleRate: 48000,
                          Specification: "MPEG4",
                        },
                      },
                      LanguageCodeControl: "FOLLOW_INPUT",
                      AudioType: 0,
                    },
                  ],
                  OutputSettings: {
                    HlsSettings: {
                      IFrameOnlyManifest: "EXCLUDE",
                    },
                  },
                  NameModifier: "360p",
                },
              ],
              OutputGroupSettings: {
                Type: "HLS_GROUP_SETTINGS",
                HlsGroupSettings: {
                  ManifestDurationFormat: "INTEGER",
                  SegmentLength: 10,
                  TimedMetadataId3Period: 10,
                  CaptionLanguageSetting: "OMIT",
                  Destination: param.output,
                  TimedMetadataId3Frame: "PRIV",
                  CodecSpecification: "RFC_4281",
                  OutputSelection: "MANIFESTS_AND_SEGMENTS",
                  ProgramDateTimePeriod: 600,
                  MinSegmentLength: 0,
                  MinFinalSegmentLength: 0,
                  DirectoryStructure: "SINGLE_DIRECTORY",
                  ProgramDateTime: "EXCLUDE",
                  SegmentControl: "SEGMENTED_FILES",
                  ManifestCompression: "NONE",
                  ClientCache: "ENABLED",
                  AudioOnlyHeader: "INCLUDE",
                  StreamInfResolution: "INCLUDE",
                },
              },
            },
            {
              CustomName: "name zzzz",
              Name: "DASH ISO",
              Outputs: [
                {
                  ContainerSettings: {
                    Container: "MPD",
                  },
                  VideoDescription: {
                    Width: 1920,
                    ScalingBehavior: "DEFAULT",
                    Height: 1080,
                    TimecodeInsertion: "DISABLED",
                    AntiAlias: "ENABLED",
                    Sharpness: 50,
                    CodecSettings: {
                      Codec: "H_264",
                      H264Settings: {
                        InterlaceMode: "PROGRESSIVE",
                        ScanTypeConversionMode: "INTERLACED",
                        NumberReferenceFrames: 3,
                        Syntax: "DEFAULT",
                        Softness: 0,
                        GopClosedCadence: 1,
                        GopSize: 90,
                        Slices: 1,
                        GopBReference: "DISABLED",
                        MaxBitrate: 4000000,
                        SlowPal: "DISABLED",
                        EntropyEncoding: "CABAC",
                        FramerateControl: "INITIALIZE_FROM_SOURCE",
                        RateControlMode: "QVBR",
                        QvbrSettings: {
                          QvbrQualityLevel: 9,
                          QvbrQualityLevelFineTune: 0,
                        },
                        CodecProfile: "MAIN",
                        Telecine: "NONE",
                        MinIInterval: 0,
                        AdaptiveQuantization: "AUTO",
                        CodecLevel: "AUTO",
                        FieldEncoding: "PAFF",
                        SceneChangeDetect: "ENABLED",
                        QualityTuningLevel: "SINGLE_PASS",
                        FramerateConversionAlgorithm: "DUPLICATE_DROP",
                        UnregisteredSeiTimecode: "DISABLED",
                        GopSizeUnits: "FRAMES",
                        ParControl: "INITIALIZE_FROM_SOURCE",
                        NumberBFramesBetweenReferenceFrames: 2,
                        RepeatPps: "DISABLED",
                        DynamicSubGop: "STATIC",
                      },
                    },
                    AfdSignaling: "NONE",
                    DropFrameTimecode: "ENABLED",
                    RespondToAfd: "NONE",
                    ColorMetadata: "INSERT",
                  },
                  NameModifier: "1080p",
                },
                {
                  ContainerSettings: {
                    Container: "MPD",
                  },
                  VideoDescription: {
                    Width: 1280,
                    ScalingBehavior: "DEFAULT",
                    Height: 720,
                    TimecodeInsertion: "DISABLED",
                    AntiAlias: "ENABLED",
                    Sharpness: 50,
                    CodecSettings: {
                      Codec: "H_264",
                      H264Settings: {
                        InterlaceMode: "PROGRESSIVE",
                        ScanTypeConversionMode: "INTERLACED",
                        NumberReferenceFrames: 3,
                        Syntax: "DEFAULT",
                        Softness: 0,
                        GopClosedCadence: 1,
                        GopSize: 90,
                        Slices: 1,
                        GopBReference: "DISABLED",
                        MaxBitrate: 2500000,
                        SlowPal: "DISABLED",
                        EntropyEncoding: "CABAC",
                        FramerateControl: "INITIALIZE_FROM_SOURCE",
                        RateControlMode: "QVBR",
                        QvbrSettings: {
                          QvbrQualityLevel: 9,
                          QvbrQualityLevelFineTune: 0,
                        },
                        CodecProfile: "MAIN",
                        Telecine: "NONE",
                        MinIInterval: 0,
                        AdaptiveQuantization: "AUTO",
                        CodecLevel: "AUTO",
                        FieldEncoding: "PAFF",
                        SceneChangeDetect: "ENABLED",
                        QualityTuningLevel: "SINGLE_PASS",
                        FramerateConversionAlgorithm: "DUPLICATE_DROP",
                        UnregisteredSeiTimecode: "DISABLED",
                        GopSizeUnits: "FRAMES",
                        ParControl: "INITIALIZE_FROM_SOURCE",
                        NumberBFramesBetweenReferenceFrames: 2,
                        RepeatPps: "DISABLED",
                        DynamicSubGop: "STATIC",
                      },
                    },
                    AfdSignaling: "NONE",
                    DropFrameTimecode: "ENABLED",
                    RespondToAfd: "NONE",
                    ColorMetadata: "INSERT",
                  },
                  NameModifier: "720p",
                },
                {
                  ContainerSettings: {
                    Container: "MPD",
                  },
                  VideoDescription: {
                    Width: 854,
                    ScalingBehavior: "DEFAULT",
                    Height: 480,
                    TimecodeInsertion: "DISABLED",
                    AntiAlias: "ENABLED",
                    Sharpness: 50,
                    CodecSettings: {
                      Codec: "H_264",
                      H264Settings: {
                        InterlaceMode: "PROGRESSIVE",
                        ScanTypeConversionMode: "INTERLACED",
                        NumberReferenceFrames: 3,
                        Syntax: "DEFAULT",
                        Softness: 0,
                        GopClosedCadence: 1,
                        GopSize: 90,
                        Slices: 1,
                        GopBReference: "DISABLED",
                        MaxBitrate: 1500000,
                        SlowPal: "DISABLED",
                        EntropyEncoding: "CABAC",
                        FramerateControl: "INITIALIZE_FROM_SOURCE",
                        RateControlMode: "QVBR",
                        QvbrSettings: {
                          QvbrQualityLevel: 9,
                          QvbrQualityLevelFineTune: 0,
                        },
                        CodecProfile: "MAIN",
                        Telecine: "NONE",
                        MinIInterval: 0,
                        AdaptiveQuantization: "AUTO",
                        CodecLevel: "AUTO",
                        FieldEncoding: "PAFF",
                        SceneChangeDetect: "ENABLED",
                        QualityTuningLevel: "SINGLE_PASS",
                        FramerateConversionAlgorithm: "DUPLICATE_DROP",
                        UnregisteredSeiTimecode: "DISABLED",
                        GopSizeUnits: "FRAMES",
                        ParControl: "INITIALIZE_FROM_SOURCE",
                        NumberBFramesBetweenReferenceFrames: 2,
                        RepeatPps: "DISABLED",
                        DynamicSubGop: "STATIC",
                      },
                    },
                    AfdSignaling: "NONE",
                    DropFrameTimecode: "ENABLED",
                    RespondToAfd: "NONE",
                    ColorMetadata: "INSERT",
                  },
                  NameModifier: "480p",
                },
                {
                  ContainerSettings: {
                    Container: "MPD",
                  },
                  VideoDescription: {
                    Width: 640,
                    ScalingBehavior: "DEFAULT",
                    Height: 360,
                    TimecodeInsertion: "DISABLED",
                    AntiAlias: "ENABLED",
                    Sharpness: 50,
                    CodecSettings: {
                      Codec: "H_264",
                      H264Settings: {
                        InterlaceMode: "PROGRESSIVE",
                        ScanTypeConversionMode: "INTERLACED",
                        NumberReferenceFrames: 3,
                        Syntax: "DEFAULT",
                        Softness: 0,
                        GopClosedCadence: 1,
                        GopSize: 90,
                        Slices: 1,
                        GopBReference: "DISABLED",
                        MaxBitrate: 800000,
                        SlowPal: "DISABLED",
                        EntropyEncoding: "CABAC",
                        FramerateControl: "INITIALIZE_FROM_SOURCE",
                        RateControlMode: "QVBR",
                        QvbrSettings: {
                          QvbrQualityLevel: 9,
                          QvbrQualityLevelFineTune: 0,
                        },
                        CodecProfile: "MAIN",
                        Telecine: "NONE",
                        MinIInterval: 0,
                        AdaptiveQuantization: "AUTO",
                        CodecLevel: "AUTO",
                        FieldEncoding: "PAFF",
                        SceneChangeDetect: "ENABLED",
                        QualityTuningLevel: "SINGLE_PASS",
                        FramerateConversionAlgorithm: "DUPLICATE_DROP",
                        UnregisteredSeiTimecode: "DISABLED",
                        GopSizeUnits: "FRAMES",
                        ParControl: "INITIALIZE_FROM_SOURCE",
                        NumberBFramesBetweenReferenceFrames: 2,
                        RepeatPps: "DISABLED",
                        DynamicSubGop: "STATIC",
                      },
                    },
                    AfdSignaling: "NONE",
                    DropFrameTimecode: "ENABLED",
                    RespondToAfd: "NONE",
                    ColorMetadata: "INSERT",
                  },
                  NameModifier: "360p",
                },
                {
                  ContainerSettings: {
                    Container: "MPD",
                  },
                  AudioDescriptions: [
                    {
                      AudioTypeControl: "FOLLOW_INPUT",
                      AudioSourceName: "Audio Selector 1",
                      CodecSettings: {
                        Codec: "AAC",
                        AacSettings: {
                          AudioDescriptionBroadcasterMix: "NORMAL",
                          Bitrate: 96000,
                          RateControlMode: "CBR",
                          CodecProfile: "LC",
                          CodingMode: "CODING_MODE_2_0",
                          RawFormat: "NONE",
                          SampleRate: 48000,
                          Specification: "MPEG4",
                        },
                      },
                      LanguageCodeControl: "FOLLOW_INPUT",
                    },
                  ],
                  NameModifier: "Audio",
                },
              ],
              OutputGroupSettings: {
                Type: "DASH_ISO_GROUP_SETTINGS",
                DashIsoGroupSettings: {
                  SegmentLength: 30,
                  MinFinalSegmentLength: 0,
                  Destination: param.output,
                  FragmentLength: 2,
                  SegmentControl: "SEGMENTED_FILES",
                  MpdProfile: "MAIN_PROFILE",
                  HbbtvCompliance: "NONE",
                },
              },
            },
          ],
          AdAvailOffset: 0,
          Inputs: [
            {
              AudioSelectors: {
                "Audio Selector 1": {
                  Offset: 0,
                  DefaultSelection: "DEFAULT",
                  ProgramSelection: 1,
                },
              },
              VideoSelector: {
                ColorSpace: "FOLLOW",
                Rotate: "DEGREE_0",
                AlphaBehavior: "DISCARD",
              },
              FilterEnable: "AUTO",
              PsiControl: "USE_PSI",
              FilterStrength: 0,
              DeblockFilter: "DISABLED",
              DenoiseFilter: "DISABLED",
              InputScanType: "AUTO",
              TimecodeSource: "ZEROBASED",
              FileInput: param.input,
            },
          ],
        },
        AccelerationSettings: {
          Mode: "DISABLED",
        },
        StatusUpdateInterval: "SECONDS_60",
        Priority: 0,
        HopDestinations: [],
      };
    }
  }

  async createJob() {
    let endpointPromise = await new AWS.MediaConvert({
      apiVersion: "2017-08-29",
    })
      .createJob(this.params)
      .promise();

    return true;
  }
}

// const a = new AWSMediaConvertService('1')
// a.createJob()
