version: '3.2'
services:
  redis:
    container_name: dududu-redis
    restart: on-failure
    image: redis:6.0.8
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./redis_data:/data
    command: "redis-server --requirepass ${REDIS_PASSWORD}"
networks:
  default:
    name: '${NETWORK_NAME}'
